const $=(id)=>document.getElementById(id);
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=(msg,bad=false)=>{const t=$('toast');t.textContent=msg;t.className=`toast show${bad?' bad':''}`;clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>t.className='toast',3600)};
async function api(path,options={}){const r=await fetch(path,{cache:'no-store',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.detail||`${r.status} ${r.statusText}`);return b;}
const arr=(v)=>Array.isArray(v)?v:(Array.isArray(v?.items)?v.items:Array.isArray(v?.data)?v.data:Array.isArray(v?.sources)?v.sources:[]);
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v)=>Math.max(0,Math.min(100,num(v)));
const status=(v)=>String(v||'').toLowerCase();
const clock=(v)=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});};
const dateTime=(v)=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});};
const ago=(v)=>{if(!v)return'未知';const d=new Date(v);if(Number.isNaN(d.getTime()))return'未知';const m=Math.max(0,Math.round((Date.now()-d.getTime())/60000));if(m<1)return'刚刚';if(m<60)return`${m} 分钟前`;const h=Math.round(m/60);return h<24?`${h} 小时前`:`${Math.round(h/24)} 天前`;};
const today=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const districts=['黄浦区','徐汇区','长宁区','静安区','普陀区','虹口区','杨浦区','闵行区','宝山区','嘉定区','浦东新区','金山区','松江区','青浦区','奉贤区','崇明区'];
let cache={tasks:null,local:null,daily:null,sources:[],system:null};

function tickClock(){const d=new Date();const t=d.toLocaleTimeString('zh-CN',{hour12:false});$('topClock').textContent=`${d.toLocaleDateString('zh-CN')} ${t}`;$('heroUpdated').textContent=t;}
function initDistricts(){const root=$('districtGrid');root.innerHTML=districts.map(d=>`<div class="district-chip${d==='静安区'?' active':''}" data-district="${d}">${d}</div>`).join('');}
function setRing(id,value){const el=$(id);const p=clamp(value);el.style.setProperty('--p',p);el.querySelector('span').textContent=Number.isFinite(Number(value))?`${Math.round(p)}%`:'—';}
function extractDeep(obj,terms){let best=null;const wanted=terms.map(x=>x.toLowerCase());function walk(v,path=[]){if(v==null||best!==null)return;if(typeof v==='object'){for(const [k,val] of Object.entries(v)){const kp=[...path,k];const joined=kp.join('.').toLowerCase();if(wanted.every(w=>joined.includes(w))&&Number.isFinite(Number(val))){best=Number(val);return;}walk(val,kp);if(best!==null)return;}}}walk(obj);return best;}
function sourceTitle(row){return row?.title||row?.name||row?.headline||row?.url||'未命名证据';}
function sourceName(row){return row?.source_name||row?.source||row?.publisher||row?.domain||(()=>{try{return new URL(row?.url||'').hostname}catch{return'本地来源'}})();}
function sourceTime(row){return row?.published_at||row?.created_at||row?.updated_at||row?.fetched_at||row?.timestamp;}
function sourceScore(row){return num(row?.relevance_score??row?.score??row?.relevance,0);}

async function loadBuild(){try{const d=await api('/api/build');$('buildBadge').textContent=`UI 4.13 · BE ${(d.build_sha||'unknown').slice(0,8)}`;}catch{$('buildBadge').textContent='UI 4.13 · BE unknown';}}
async function loadTasks(){const data=await api('/api/intelligence/tasks?limit=240');cache.tasks=data;renderTasks();}
function renderTasks(){const data=cache.tasks||{},q=data.queue||{},current=q.current||null,queued=q.queued||[],failed=data.failed||[],counts=data.counts||{};const running=current?[current,...(q.extra_running||[])]:[];
  $('metricQueue').textContent=running.length+queued.length;$('metricQueueSub').textContent=current?`当前 ${Math.round(num(current.progress_percent))}% · 排队 ${queued.length}`:`等待 ${queued.length}`;
  $('countRunning').textContent=running.length;$('countQueued').textContent=queued.length;$('countFailed').textContent=failed.length;$('countDone').textContent=num(counts.completed??counts.success,0);
  $('pipeAI').textContent=running.length+queued.length;$('pipeAIStatus').textContent=current?`当前 ${Math.round(num(current.progress_percent))}%`:'串行 1×';
  const rows=[...running,...queued,...failed].slice(0,8);$('taskRows').innerHTML=rows.length?rows.map(r=>{const s=status(r.status)|| (running.includes(r)?'running':queued.includes(r)?'queued':'failed');const pct=clamp(r.progress_percent);const eta=r.eta_complete_at?clock(r.eta_complete_at):(r.eta_seconds?`${Math.round(num(r.eta_seconds)/60)} 分`:'—');return`<tr data-filter="${esc((r.label||r.topic_name||r.topic||'')+' '+s)}"><td class="name">${esc(r.label||r.topic_name||r.topic||(r.job_id?`AI ${String(r.job_id).slice(0,8)}`:`Run #${r.id||'—'}`))}</td><td><span class="status-tag ${esc(s)}">${esc(s||'unknown')}</span></td><td><div class="progress-line"><i style="width:${pct}%"></i></div></td><td>${esc(eta)}</td><td>${esc(clock(r.updated_at||r.heartbeat_at||r.started_at))}</td><td><a class="task-link" href="/insights.html#queue">查看</a></td></tr>`}).join(''):'<tr><td colspan="6" class="empty">当前没有任务。</td></tr>';
  if(q.serial_violation){$('taskWarning').classList.remove('hidden');$('taskWarning').textContent='检测到重 AI 并发异常，请进入任务监控检查旧 Worker。';$('systemOverall').textContent='AI 串行异常';}else{$('taskWarning').classList.add('hidden');}
}
async function loadLocal(){const d=await api(`/api/intelligence/local/coverage?day=${encodeURIComponent(today())}`);cache.local=d;renderLocal();}
function renderLocal(){const d=cache.local||{},by=d.by_district||{},covered=Object.keys(by);const total=num(d.total);const sanle=num(d.sanle_jiangning_count);$('metricEvidence').textContent=total.toLocaleString();$('metricEvidenceSub').textContent=d.collector?`新增 ${num(d.collector.inserted)} · 去重 ${num(d.collector.duplicates)}`:'等待本地采集';$('metricDistricts').textContent=`${covered.length}/16`;$('metricSanle').textContent=sanle.toLocaleString();$('focusEvidence').textContent=sanle;$('focusDistricts').textContent=covered.length;$('focusCollector').textContent=d.collector?'已完成':'等待';$('pipeCollected').textContent=num(d.collector?.inserted??total);$('pipeFiltered').textContent=total;$('pipeCollectedStatus').textContent=d.collector?'已完成':'等待';document.querySelectorAll('.district-chip').forEach(el=>el.classList.toggle('covered',covered.includes(el.dataset.district)));}
async function loadDaily(){try{const d=await api(`/api/intelligence/daily/${encodeURIComponent(today())}`);cache.daily=d;renderDaily();}catch(e){cache.daily={exists:false};renderDaily();}}
function renderDaily(){const d=cache.daily||{};const done=!!d.exists;$('metricReport').textContent=done?'1/1':'0/1';$('metricReportSub').textContent=done?`生成 ${clock(d.generated_at)}`:'等待当天任务完成';$('reportProgress').style.width=done?'100%':'0%';$('pipeReport').textContent=done?'1/1':'0/1';$('pipeReportStatus').textContent=done?'已生成':'等待';}
async function loadSources(){try{cache.sources=arr(await api('/api/sources'));renderSources();}catch{cache.sources=[];renderSources();}}
function renderSources(){const list=cache.sources.slice().sort((a,b)=>new Date(sourceTime(b)||0)-new Date(sourceTime(a)||0));$('pipeEvents').textContent=list.length?Math.min(list.length,60):'—';const top=list.slice(0,10);$('eventList').innerHTML=top.length?top.map((r,i)=>{const sc=sourceScore(r);const sev=sc>=.85?'high':sc>=.6?'mid':'low';const label=sc?`${Math.round(sc*100)}%`:(i<3?'高':i<7?'中':'低');return`<li data-filter="${esc(sourceTitle(r)+' '+sourceName(r))}"><span class="event-num">${i+1}</span><div class="event-main"><div class="event-title">${esc(sourceTitle(r))}</div><div class="event-meta">${esc(sourceName(r))} · ${esc(ago(sourceTime(r)))}</div></div><span class="severity ${sev}">${esc(label)}</span></li>`}).join(''):'<li class="empty">暂无证据数据。</li>';
  const groups=new Map();for(const r of list.slice(0,120)){const n=sourceName(r)||'未知来源',t=sourceTime(r);if(!groups.has(n)||new Date(t||0)>new Date(groups.get(n)||0))groups.set(n,t);}const fresh=[...groups.entries()].slice(0,8);$('freshnessList').innerHTML=fresh.length?fresh.map(([n,t])=>{const mins=t?Math.max(0,(Date.now()-new Date(t).getTime())/60000):9999;const good=mins<180;return`<div class="fresh-row"><span>${esc(n)}</span><span class="fresh-time">${esc(ago(t))}</span><span class="fresh-status ${good?'good':'warn'}">● ${good?'良好':'待更新'}</span></div>`}).join(''):'<div class="empty">暂无来源数据。</div>';
}
async function loadSystem(){try{const d=await api('/api/system/status');cache.system=d;renderSystem();}catch{cache.system={};renderSystem();}}
function renderSystem(){const d=cache.system||{};const cpu=extractDeep(d,['cpu','percent'])??extractDeep(d,['cpu','usage']);const ram=extractDeep(d,['memory','percent'])??extractDeep(d,['ram','percent'])??extractDeep(d,['memory','usage']);const gpu=extractDeep(d,['gpu','percent'])??extractDeep(d,['gpu','util']);setRing('cpuRing',cpu);setRing('gpuRing',gpu);$('cpuValue').textContent=cpu==null?'—':`${Math.round(cpu)}%`;$('gpuValue').textContent=gpu==null?'—':`${Math.round(gpu)}%`;$('ramValue').textContent=ram==null?'—':`${Math.round(clamp(ram))}%`;$('ramBar').style.width=ram==null?'0%':`${clamp(ram)}%`;const text=JSON.stringify(d).toLowerCase();const ollamaOk=text.includes('ollama')&&!text.includes('ollama":"down')&&!text.includes('ollama":"error');$('ollamaValue').textContent=ollamaOk?'运行中':'检测';$('ollamaBar').style.width=ollamaOk?'100%':'55%';if(text.includes('error')||text.includes('unhealthy')){$('systemOverall').textContent='部分服务异常';}else if(!cache.tasks?.queue?.serial_violation){$('systemOverall').textContent='系统运行正常';}}
async function runCollect(){const b=$('runCollectBtn');b.disabled=true;b.textContent='已加入采集队列…';try{const r=await api(`/api/intelligence/local/collect?day=${encodeURIComponent(today())}`,{method:'POST'});toast(`上海本地采集已排队 ${r.task_id||''}`);setTimeout(refreshAll,3500);}catch(e){toast(e.message,true);}finally{setTimeout(()=>{b.disabled=false;b.textContent='立即采集'},1400)}}
function filterVisible(q){q=q.trim().toLowerCase();document.querySelectorAll('[data-filter]').forEach(el=>{el.style.display=!q||el.dataset.filter.toLowerCase().includes(q)?'':'none';});}
async function refreshAll(){await Promise.allSettled([loadBuild(),loadTasks(),loadLocal(),loadDaily(),loadSources(),loadSystem()]);}
function initSidebar(){const sb=$('sidebar');const toggle=()=>sb.classList.toggle('collapsed');$('collapseBtn').addEventListener('click',toggle);$('sidebarToggle').addEventListener('click',toggle);}
initDistricts();initSidebar();tickClock();setInterval(tickClock,1000);$('runCollectBtn').addEventListener('click',runCollect);$('globalSearch').addEventListener('input',e=>filterVisible(e.target.value));refreshAll();setInterval(refreshAll,15000);
